---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dev
  name: fe-piattaforma-deployment
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: fe-piattaforma
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: fe-piattaforma
    spec:
      containers:
        - name: fe-piattaforma
          image: ${ECR_REPOSITORY}:${IMAGE_TAG}
          ports:
            - containerPort: 80
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  namespace: dev
  name: service-ingress-fe-dev
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: fe-piattaforma
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: dev
  name: ingress-fe-dev
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    external-dns.alpha.kubernetes.io/hostname: frontend.facilitazione-dev.mitd.technology
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: service-ingress-fe-dev
              port:
                number: 80
