apiVersion: apps/v1
kind: Deployment
metadata:
  name: fe-piattaforma
  labels:
    app: fe-piattaforma
spec:
  selector:
    matchLabels:
        app: fe-piattaforma
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: fe-piattaforma
    spec:
      containers:
        - name: fe-piattaforma
          image: 848729353763.dkr.ecr.eu-central-1.amazonaws.com/test-repo01:fe-piattaforma-1.2.0
          ports:
            - containerPort: 80
              protocol: TCP
          imagePullPolicy: Always
