---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dev
  name: fe-piattaforma-deployment
  labels:
    app: fe-piattaforma
spec:
  selector:
    matchLabels:
        app: fe-piattaforma
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: fe-piattaforma
    spec:
      containers:
        - name: fe-piattaforma
          image: ${ECR_REPOSITORY}:${IMAGE_TAG}
          ports:
            - containerPort: 8080
              protocol: TCP
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  namespace: dev
  name: service-ingress-dev-2
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: fe-piattaforma
  ports:
    - name: http
      port: 8080
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: dev
  name: ingress-dev-2
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    external-dns.alpha.kubernetes.io/hostname: frontend.facilitazione-dev.mitd.technology
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: service-ingress-dev-2
              port:
                number: 8080
