version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "github-actions"
      - "dependabot"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "07:00"
      timezone: Europe/Rome

  - package-ecosystem: "npm"
    directory: "/fe-piattaforma"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "npm"
      - "dependabot"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "07:00"
      timezone: Europe/Rome

  - package-ecosystem: "maven"
    directory: "/"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "maven"
      - "dependabot"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "07:00"
      timezone: Europe/Rome
