apiVersion: apps/v1
kind: Deployment
metadata:
  name: underwater-app-jenkins
  labels:
    app: octopus-underwater-app
spec:
  selector:
    matchLabels:
        app: octopus-underwater-app
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: octopus-underwater-app
    spec:
      containers:
        - name: octopus-underwater-app
          image: 848729353763.dkr.ecr.eu-central-1.amazonaws.com/test-repo01:fe-piattaforma-1.0.0
          ports:
            - containerPort: 80
              protocol: TCP
          imagePullPolicy: Always
