export const questionarioMock = {
  form: {
    'survey-type': {
      field: 'survey-type',
      options: undefined,
      regex: 'alphaNumericInput',
      required: true,
      touched: false,
      type: 'text',
      valid: true,
      value: 'Primo accesso',
    },
    'survey-name': {
      field: 'survey-name',
      options: undefined,
      regex: 'alphaNumericInput',
      required: true,
      touched: false,
      type: 'text',
      valid: true,
      value: 'Test form',
    },
  },
  sections: [
    {
      id: 'anagraphic-section',
      questions: [
        {
          id: 'Nome',
          form: {
            'question-description': {
              field: 'question-description',
              value: 'Nome',
              valid: true,
              type: 'text',
              required: true,
              regex: 'alphaNumericInput',
              touched: false,
            },
            'question-type': {
              field: 'question-type',
              value: 'text',
              valid: true,
              type: 'text',
              required: true,
              regex: 'alphaNumericInput',
              touched: false,
            },
            'question-values': {
              field: 'question-values',
              value: '',
              valid: true,
              type: 'text',
              required: true,
              regex: 'alphaNumericInput',
              touched: false,
            },
            'question-required': {
              field: 'question-required',
              value: true,
              valid: true,
              type: 'text',
              required: true,
              regex: 'alphaNumericInput',
              touched: false,
            },
          },
        },
        {
          id: 'Cognome',
          form: {
            'question-description': {
              field: 'question-description',
              value: 'Cognome',
              valid: true,
              type: 'text',
              required: true,
              regex: 'alphaNumericInput',
              touched: false,
            },
            'question-type': {
              field: 'question-type',
              value: 'text',
              valid: true,
              type: 'text',
              required: true,
              regex: 'alphaNumericInput',
              touched: false,
            },
            'question-values': {
              field: 'question-values',
              value: '',
              valid: true,
              type: 'text',
              required: true,
              regex: 'alphaNumericInput',
              touched: false,
            },
            'question-required': {
              field: 'question-required',
              value: true,
              valid: true,
              type: 'text',
              required: true,
              regex: 'alphaNumericInput',
              touched: false,
            },
          },
        },
      ],
      sectionTitle: 'Sezione - Dati anagrafici del cittadino (obbligatoria)', 
      type: 'first',
      form: {
        'section-title': {
          field: 'section-title',
          options: undefined,
          regex: 'alphaNumericInput',
          required: true,
          touched: false,
          type: 'text',
          valid: true,
          value: 'Dati anagrafici del cittadino (obbligatoria)',
        },
        'section-visibility': {
          field: 'section-visibility',
          options: undefined,
          regex: 'alphaNumericInput',
          required: true,
          touched: false,
          type: 'text',
          valid: true,
          value: 'Solo facilitazione',
        },
      },
    },
    {
      form: {
        'section-title': {
          field: 'section-title',
          options: undefined,
          regex: 'alphaNumericInput',
          required: true,
          touched: false,
          type: 'text',
          valid: true,
          value: 'Sezione 1',
        },
        'section-visibility': {
          field: 'section-visibility',
          options: undefined,
          regex: 'alphaNumericInput',
          required: true,
          touched: false,
          type: 'text',
          valid: true,
          value: 'Solo facilitazione',
        },
      },
      id: '1651670518163',
      questions: [
        {
          id: '1651670518111',
          form: {
            'question-description': {
              field: 'question-description',
              value: 'Domanda 1',
              valid: true,
              type: 'text',
              required: true,
              regex: 'alphaNumericInput',
              touched: false,
            },
            'question-type': {
              field: 'question-type',
              value: 'text',
              valid: true,
              type: 'text',
              required: true,
              regex: 'alphaNumericInput',
              touched: false,
            },
            'question-values': {
              field: 'question-values',
              value: '',
              valid: true,
              type: 'text',
              required: true,
              regex: 'alphaNumericInput',
              touched: false,
            },
            'question-required': {
              field: 'question-required',
              value: true,
              valid: true,
              type: 'text',
              required: true,
              regex: 'alphaNumericInput',
              touched: false,
            },
          },
        },
        {
          id: '1651670518122',
          form: {
            'question-description': {
              field: 'question-description',
              value: 'Domanda 2',
              valid: true,
              type: 'text',
              required: true,
              regex: 'alphaNumericInput',
              touched: false,
            },
            'question-type': {
              field: 'question-type',
              value: 'number',
              valid: true,
              type: 'text',
              required: true,
              regex: 'alphaNumericInput',
              touched: false,
            },
            'question-values': {
              field: 'question-values',
              value: '',
              valid: true,
              type: 'text',
              required: true,
              regex: 'alphaNumericInput',
              touched: false,
            },
            'question-required': {
              field: 'question-required',
              value: true,
              valid: true,
              type: 'text',
              required: true,
              regex: 'alphaNumericInput',
              touched: false,
            },
          },
        },
        {
          id: '1651670518133',
          form: {
            'question-description': {
              field: 'question-description',
              value: 'Domanda 3',
              valid: true,
              type: 'text',
              required: true,
              regex: 'alphaNumericInput',
              touched: false,
            },
            'question-type': {
              field: 'question-type',
              value: 'select',
              valid: true,
              type: 'text',
              required: true,
              regex: 'alphaNumericInput',
              touched: false,
            },
            'question-values': {
              field: 'question-values',
              value:
                '[{"label":"valore 1","value":"valore 1"},{"label":"valore 2","value":"valore 2"},{"label":"valore 3","value":"valore 3"}]',
              valid: true,
              type: 'text',
              required: true,
              regex: 'alphaNumericInput',
              touched: false,
            },
            'question-required': {
              field: 'question-required',
              value: '',
              valid: true,
              type: 'text',
              required: true,
              regex: 'alphaNumericInput',
              touched: false,
            },
          },
        },
      ],
      sectionTitle: 'Sezione 1',
      type: 'standard',
    },
  ],
};
