name: Build FE

on:
  workflow_dispatch:

jobs:
  buildFE:
    name: Front-End Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
        
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'

      - name: Change work directory
        run: |
          cd ${{ github.workspace }}/fe-piattaforma

      - name: Modify Env File
        run: |
          echo "do something"
          pwd ; ls -al

      - name: Install dependencies
        run: |
          pwd ; ls -al
          npm install

      - name: Build
        run: |
          npm run build
