name: Build FE

on:
  workflow_dispatch:
  push:

jobs:
  buildFE:
    name: Front-End Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
        
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'

      - name: Change work directory
        run: |
          cd ${{ github.workspace }}/fe-piattaforma

      - name: Modify Env File
        run: |
          cd ${{ github.workspace }}/fe-piattaforma
          echo "do something"

      - name: Install dependencies
        run: |
          cd ${{ github.workspace }}/fe-piattaforma
          npm run prepare
          npm install

      - name: Build
        run: |
          cd ${{ github.workspace }}/fe-piattaforma
          npm run build
