name: Build BE

on:
  workflow_dispatch:
#  push:

env:
  BOT_USER: "mitd-bot"
  BOT_MAIL: "mitd-bot@example.com"

jobs:
  buildBE:
    name: Back-End Build
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ${{ github.workspace }}/ms-gestione-utente
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
        
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt-openj9'

      - name: Install Lib
        run: |
          cd ${{ github.workspace }}/lib-repdgt-shared
          mvn versions:set -DnewVersion=test
          mvn install

      - name: Set New ms-Version
        run: |
          mvn versions:set -DnewVersion=test

      - name: Build
        run: |
          mvn package -Dmaven.test.skip=true -DDB_PASSWORD=Accenture1234! -DDB_URL=jdbc:mysql://mysql-8-dev-rds.ceqxasyhnnq8.eu-central-1.rds.amazonaws.com/repdig01_dev_schema -DDB_USERNAME=be

      - name: Docker
        run: |
          docker build . \
            --file Dockerfile \
            --tag my-image-name:$(date +%s) 
            
      - name: Push pom.xml updated
        run: |
          git diff
          git config --global user.email "$BOT_MAIL"
          git config --global user.name "$BOT_USER"
          git add -A
          git commit -m "chore: update version" || exit 0
          git push
