name: Build FE

on:
  workflow_dispatch:

jobs:
  buildFE:
    name: Front-End Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
        
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'

      - name: Modify Env File
        run: |
          cd ./fe-piattaforma
          echo "do something"
          ls -al


      - name: Install dependencies
        run: |
          ls -al
          npm install

      - name: Build
        run: |
          npm run build
