name: Build FE

on:
  workflow_dispatch:
#  push:

jobs:
  buildFE:
    name: Front-End Build
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ${{ github.workspace }}/fe-piattaforma

    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
        
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'

      - name: Modify Env File
        run: |
          echo "do something"
      
      - name: File Regex Replace
        uses: mingjun97/file-regex-replace@v1
        with:
          # regex to apply(regex)
          regex: '"version":[\s\S]"[0-9].[0-9].[0-9]"'
          # flags of the regex
          flags: "gmi"
          # replacement string
          replacement: '"version": "1.1.0",'
          # Files to be replaced(regex)
          include: "package.json"
      
      - run: cat package.json | grep version
          
      - name: Build Docker Image
        run: | 
          docker build \
            --target build \
            --file Dockerfile 
            --tag my-image-name:$(date +%s)
        
