name: CI Workflow

on:
  push:
    branches:
      - 'fix/**'
      - 'feat/**'
  pull_request:
    types: [closed]
    branches:
      - 'main'
      - 'test'
      - 'develop'

jobs:
  commitlint:
    name: Commit Linter
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true) }}
    steps:
    - uses: actions/checkout@v3.0.2
      with:
        ref: ${{ github.event.inputs.BRANCH }}
        lfs: 'true'
    
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 'lts/*'

    - name: Install Commitlint
      run: |
          npm install --save-dev @commitlint/{cli,config-conventional}

    - name: Lint commit message
      run: |
          npx commitlint --from=HEAD~1

  changesFE:
    name: FE Changes detection
    if: ${{ github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true) }}
    runs-on: ubuntu-latest
    outputs:
      frontend: ${{ steps.filter.outputs.frontend }}
      backend: ${{ steps.filter.outputs.backend }}
    steps:
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          frontend:
            - 'fe-frontend/**'
#          backend:
#            - 'ms-ente/**'
#            - 'ms-open-data/**'
#            - 'ms-programma-progetto/**'
#            - 'ms-questionario-cittadino/**'
#            - 'ms-utente/**'

  changesBE:
    name: BE Changes detection
    if: ${{ github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true) }}
    runs-on: ubuntu-latest
    outputs:
      modules: ${{ steps.filter.outputs.changes }}
    steps:
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          ms-ente: ms-ente/
          ms-open-data: ms-open-data/
          ms-programma-progetto: ms-programma-progetto/
          ms-questionario-cittadino: ms-questionario-cittadino/
          ms-utente: ms-utente/

  sca:
    name: CodeQL
    if: ${{ github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true) }}
    runs-on: ubuntu-latest
    ...

  buildFE:
    needs: changesFE
    if: ${{ needs.changes.outputs.frontend == 'true' && ( github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true) ) }}
    name: Front-End Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
        with:
          ref: ${{ github.event.inputs.BRANCH }}
          lfs: 'true'

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      
      - name: Build
        ...

  buildBE:
    needs: changesBE
    if: ${{ fromJSON(needs.changes.outputs.packages) !== null && ( github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true) ) }}
#    if: ${{ needs.changes.outputs.backend == 'true' && ( github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true) ) }}
    name: Back-End Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ...
        module: ${{ fromJSON(needs.changes.outputs.modules) }}
        include:
          - module: "ms-ente"
            datacenter: "site-a"
            ...
    steps:
      - uses: actions/checkout@v3.0.2
        with:
          ref: ${{ github.event.inputs.BRANCH }}
          lfs: 'true'
    
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build
        if: ${{ matrix.module == 'ms-ente' }}
        ...
