name: Release

on:
  workflow_dispatch:
    inputs:
      release-type:
        description: 'Type of run to be performed'
        required: true
        type: choice
        options: 
        - dryrun
        - run

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  # eseguito sempre
  dry-release:
    runs-on: ubuntu-latest
    steps:
    - name: Release dry-run
      run: |
        echo "Release dry-run"

  build:
    runs-on: ubuntu-latest
      strategy:
        matrix:
          module: ['fe-frontend','ms-ente', 'ms-open-data','ms-programma-progetto','ms-questionario-cittadino','ms-utente']
      steps:
      - name: Checkout
        run: echo " "
      - name: Node build  
        if: ${{ matrix.module == 'fe-frontend' }}
        run: echo "node build"  
      - name: Maven build 
        if: ${{ matrix.module != 'fe-frontend' }}
        run: echo " "    
      - name: Configure AWS credentials
        run: echo " "
      - name: Login to Amazon ECR
        run: echo " "    
      - name: Build, tag, and push the image to Amazon ECR
        run: echo " "

  # eseguito quando release-type è run --> da capire se serve un dry-run. in caso affermativo capire l'impatto sugli altri job 
  release:
    needs: ['dry-release','build']
    runs-on: ubuntu-latest
    steps:
    - name: Release Github
      run: echo " "
    - name: Deploy EKS
      run: echo " "

